site_name: 300cs
site_url: https://isla23.github.io/300dzzCS/
site_description: 300cs
repo_url: https://github.com/isla23/300dzzCS
repo_name: 300dzzCS
edit_uri: https://github.com/isla23/300dzzCS/edit/main/


# 自定义CSS
extra_css:
  - stylesheets/extra.css

plugins:
  - shortcode

theme:
  name: material
  language: zh
  logo: assets/pic/logo_256.png
  favicon: assets/pic/logo_256.png
  # 主题配色
  palette: 
    # 1. 浅色模式
    - scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: 黄区配色 (Dark Mode)
    # 2. 深色模式
    - scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: 白区配色 (Light Mode)
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MaaGF1/MaaGF1
      name: GitHub 仓库

# 目录结构
nav:
  - 300cs: tutorial/300cs/cs_1.0.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html