site_name: MaaGF1 文档
site_url: https://maagf1.github.io/docs/
site_description: 少女前线PC端自动化项目文档
repo_url: https://github.com/MaaGF1/MaaGF1
repo_name: MaaGF1/MaaGF1
edit_uri: https://github.com/MaaGF1/docs/edit/main/

# 自定义CSS
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: zh
  logo: assets/pic/logo_256.png
  favicon: assets/pic/logo_256.png
  # 主题配色
  palette: 
    # 1. 浅色模式
    - scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: 黄区配色 (Dark Mode)
    # 2. 深色模式
    - scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: 白区配色 (Light Mode)
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MaaGF1/MaaGF1
      name: GitHub 仓库

# 目录结构
nav:
  - 首页: index.md
  - 基础知识:
    - 下载并运行: tutorial/begin/下载并运行.md
    - 下载并运行-2.0: tutorial/begin/下载并运行_v2.md
    - 常见问题: tutorial/begin/FAQ.md
  - 资源获取:
    - 兵棋挂机: tutorial/base/兵棋挂机.md
    - 灰域探查: tutorial/resource/自动打灰.md
    - 指挥官后勤: tutorial/resource/指挥官后勤.md
    - 捡垃圾: tutorial/resource/捡垃圾.md
    - 炼金: tutorial/resource/炼金.md
    - 零元购: tutorial/resource/零元购.md
    - DLZ版自动灰域: tutorial/resource/DLZ版自动灰域.md
  - 练级指南:
    - 13-4: tutorial/experience/13-4.md
    - 8-1N: tutorial/experience/8-1n.md
    - 裂变链接练级: tutorial/experience/跑步机.md
  - 救援打捞:
    - 人形救援: tutorial/rescue/人形救援.md
    - 装备打捞: tutorial/rescue/装备打捞.md
    - 循演战役: tutorial/rescue/循演战役.md
  - 进阶指南:
    - 虚拟显示器: advanced/虚拟显示器.md
  - 300cs: 300cs/cs_1.0.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html